// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.DBCONTEXT;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(MainDBContext))]
    partial class MainDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Department Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Department Name");

                    b.HasKey("Id")
                        .HasName("pk_DepId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("Employee Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date Of Joining");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("Varchar(100)")
                        .HasColumnName("Employee Name");

                    b.Property<string>("EmpPicture")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Picture");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Employee Location");

                    b.HasKey("Id")
                        .HasName("pk_Emp_Id");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
