// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using model_popup.Models;

#nullable disable

namespace model_popup.Migrations
{
    [DbContext(typeof(BankContext))]
    partial class BankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("model_popup.Models.Bank_Details", b =>
                {
                    b.Property<int>("Account_number")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(14)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Account_number"));

                    b.Property<int>("IFSC_Code")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<int>("Mobile_Number")
                        .HasColumnType("int");

                    b.Property<string>("Name_of_customer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Zip_code")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.HasKey("Account_number");

                    b.ToTable("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
